### PR TITLE
Frontend/mcw 23 signup page

### PR DESCRIPTION
**Pull request by Yellowatch**
I have created the signup page that is responsive to phones and desktop.

We have to make it responsive for tablets too.

I believe we should remove the username section as we already have first and last name.

I also haven't done the sending a request to the backend API yet as that hasn't been pushed to the develop branch yet. Once that's done, I'll update this accordingly.

Kim, would you be able to do the frontend tests for this?

Please let me know what you think!

image

image

image

image

image

### CODE REVIEW

**Comment by kimt12531** [comment]
I've added fixes for responsivity in my PR. I would suggest merging that first so that you could have the watercolor background on these pages too! I also have a button called SquareButton that you could use for these as well.

**Comment by Yellowatch** [comment]
I also completely forgot to mention, I was playing around with popups and made one for the terms and conditions. I reckon a popup is better than sending the user to the t&cs page as they wont lose their progress in signing up. We'll see how we can connect the popup data to the backend in the next sprint. If you guys think this is bad, we can change it, I dont mind.
image

image

**Review by quangminhduong — COMMENTED** [review]
Was about to say that the design of log in and sign up look so difference to each other but then I notice that you already mentioned that you will change this so I guess I will wait then!

**Comment by kimt12531** [comment]
> I also completely forgot to mention, I was playing around with popups and made one for the terms and conditions. I reckon a popup is better than sending the user to the t&cs page as they wont lose their progress in signing up. We'll see how we can connect the popup data to the backend in the next sprint. If you guys think this is bad, we can change it, I dont mind. image
> 
> image

As mentioned in the Figma, the pop up terms and conditions is a great idea. The styling will not be too difficult to change if the client approves of the new contact us form style.

**Review by kimt12531 — APPROVED** [review]
LGTM

**Review by quangminhduong — APPROVED** [review]
Good!

**Pull request merged**
