### PR TITLE
Feature/mcw 34 discounts

### PR DESCRIPTION
**Pull request by Yellowatch**
Now when a user signs up, their account also creates a Stripe Customer, which is then used for checkout and also can limit Promotions to first time purchases per user.

Please test this thoroughly as I had lots of merging issues!

image

According to the above image, the email section is autofilled based on the customer, and the promotion says invalid as the customer had used this promotion before.

### CODE REVIEW

**Comment by quangminhduong** [comment]
I got this error when trying to run it

image

**Comment by Yellowatch** [comment]
Fixed payment success styling:

image

image

**Review by quangminhduong — APPROVED** [review]
LGMT!

**Review by kimt12531 — APPROVED** [review]
LGTM

**Pull request merged**
