### PR TITLE
Back end/mcw 22 sign up authentication

### PR DESCRIPTION
**Pull request by quangminhduong**
MCW 22

To test it, make sure to activate the virtual environment first, then navigate to backend and run `python manage.py runserver`.

Next, navigate to `api/register/` in your url and input the following json data into "Content":

`
{
            "username": "",
            "email": "",
            "password1": "",
            "password2": ""
} 
`

Feel free to swap the content inside "" to anything you want. If input properly, you will receive this message:

'message': 'User registered successfully'

Then, navigate to `/admin` and log in with the following info:

username: "admin"
password: "minh3000"

Click on the Users to see if your user has been created or not

Edit 1: If you run this server for the first time, after you activate the `dar` virtual environment, you need to install the project's required packages with the following command: `pip install -r requirements.txt`. Then, you can start the server at ease.

Edit 2: I have made also make email to be unique, which mean that the username and email must be unique for each user, feel free to test it out. I have also created new fields to input first and last name, which mean the test form should now be in this format:

 `
{"username": "","email": "","first_name": "","last_name": "","password1": "","password2": ""} 
`

Edit 3: As requested, I have removed the username and use only email instead. But Django built in authentication function require `username` as unique key so I remove `email` instead but `username` will only take input as email form instead:

 `
{"username": "","first_name": "","last_name": "","password1": "","password2": ""} 
`

Edit 4: I have modified the table multiple times so the admin account will not work anymore, you can create your own admin account before starting the server with the following command: `python manage.py createsuperuser`. Then, feel free to use any details that you want

### CODE REVIEW

**Review by kimt12531 — APPROVED** [review]
LGTM!

**Comment by Yellowatch** [comment]
How I ran backend on windows:
1. Ran vs code as admin
2. switched from powershell to cmd
3. made sure python is installed
4. py -m pip install Django
5. dar\Scripts\activate.bat
6. pip install -r requirements.txt
7. cd backend
8. python manage.py runserver

**Review by Yellowatch — APPROVED** [review]
Well done!

**Comment by Yellowatch** [comment]
Make sure you run pip install -r requirements.txt

**Pull request merged**
