### PR TITLE
chore/styling revisions

### PR DESCRIPTION
**Pull request by kimt12531**
You could see the messenger wired to the Magnolia Cake Facebook on this testing environment: https://chore-styling-revisions.d33cj0ysv7a0gd.amplifyapp.com/ 

Updates:
- Styling for all Popups
- Chat plugin for Magnolia Cake Facebook (I can guarantee it will work for the official domain as well but we could check again after this is merged - keep in mind it takes a few seconds to come up)
- New Carousel and Welcome Section styles and content
- Fixes for navbar styling and rendering
- Removing the business name in the header and replacing the home tab with the logo
- Replacing 'view cart' with cart svg
- Banner image and admin can change the photo

### CODE REVIEW

**Comment by Yellowatch** [comment]
Where's the user profile page on larger screens?
image

**Comment by kimt12531** [comment]
> Where's the user profile page on larger screens? image

I'll add it back in

**Review by quangminhduong — APPROVED** [review]
Look nice!

**Review by Yellowatch — APPROVED** [review]
Very nice

**Pull request merged**
