### PR TITLE
Mcw 35 payment page

### PR DESCRIPTION
**Pull request by quangminhduong**
Implemented stripe to handle payment. To test it, you need to add some item to your cart first:

image

Then, click on view cart then proceed to payment, please note that this button will only appear if you are logged in and the style of this cart table will be modify later:

image

The stripe secure payment gateway will open, you can use google pay, link or input your own credit card in to test, it won't charge you anything:

image

Alternatively, if you want to be safe, you can also use the test card from this site: `https://stripe.com/docs/testing?testing-method=card-numbers#cards`. For now, as payment success, you will receive the following alert then you will be redirect to the homepage when close it. There is a problem where I have to close it twice before it redirect me to the homepage and I don't know how to fix it, let me know if any of you have any idea on how it would work:

image

After this, I will improve it by email the receipt to the user's as they made a successful payment

### CODE REVIEW

**Comment by kimt12531** [comment]
Can we have the total include the extra 1.75% + 30c fee?

**Review by Yellowatch — APPROVED** [review]

**Comment by Yellowatch** [comment]
Wait, what is the purpose of the payment page? Doesn't the cart do that anyway? Also, we need a payment page for the workshop videos

**Comment by quangminhduong** [comment]
> Wait, what is the purpose of the payment page? Doesn't the cart do that anyway? Also, we need a payment page for the workshop videos

The payment page is actually Stripe built-in checkout form to handle secure credit card payment, the cart is there for user to manage their chosen item first before sending to the backend, which then can be used to open a checkout session. We need both since each of the page have its own use.

**Comment by quangminhduong** [comment]
> Can we have the total include the extra 1.75% + 30c fee?

I have read through the stripe document and notice that the user does not have to pay any extra service fees as they paid through the Stripe's payment gateway but instead, the amount of money the shop owner can receive will get deducted with that amount, on the other word, it is the shop owner who has to pay for the transaction fees at the end. However, Stripe still allow shop owner to increase the price via a formula to have their customer to pay for this fees instead, which I have implemented on the latest commit

**Review by kimt12531 — APPROVED** [review]

**Pull request merged**
