### PR TITLE
front-end/MCW-17-homepage-navbar

### PR DESCRIPTION
**Pull request by kimt12531**
[MCW17](https://student-s3849677.atlassian.net/browse/MCW-17)

Packages were added to the frontend app: react-router-dom and hamburger-react. Please do 'npm i' before 'npm start'.

Added a Navbar with routes to a Coming Soon page as a placeholder. 
The homepage also has placeholder text. 
Tabs are managed in `tabs.json`.
Navbar is responsive to desktop and mobile. 

Added login and sign up in the header.
Please refer to `constants.js` when routing sign-up and login pages.
Header sticks to top even when scrolling.

Added a Footer with working social media links (opens in new tab) and sections.
Other sections have placeholder content.

Some styling was added as demonstration, but not finalized until approved by Product Owner. Please refer to the screenshots below.

- Page layout (header, footer):
image

- Hover Navbar:
image

- Tabs (e.g., Online Store):
image

- Mobile:
image
image

### CODE REVIEW

**Comment by quangminhduong** [comment]
Look good with me!

**Review by quangminhduong — COMMENTED** [review]
Look good with me!

**Review by quangminhduong — APPROVED** [review]

**Comment by quangminhduong** [comment]
Your latest update on the home page look very nice, but I think the spacing for the footer is a little bit uneven, it could be that my monitor has a different resolution with yours so it display differently, therefore, I think it better to make the space to be flex on any resolution!
image

**Review by Yellowatch — APPROVED** [review]
Very nice!

**Pull request merged**
