### PR TITLE
Fix/mcw 355 get a quote

### PR DESCRIPTION
**Pull request by quangminhduong**
### Major fixes:
- Get a quote form can now be save to the database and view by the admin.

### Minor fixes:
- Added bar loader when submit the form
- Disable the submit button while loading to prevent the user from spamming the form
- Successful submission will navigate the user back to the homepage
- Date of event can only be selected from the current time onward

### CODE REVIEW

**Comment by kimt12531** [comment]
For some reason, I cannot see new quote objects in the backend app when I filled out the form. Does it take a while before it shows up?

**Comment by quangminhduong** [comment]
> For some reason, I cannot see new quote objects in the backend app when I filled out the form. Does it take a while before it shows up?

If it the case, try `python manage.py makemigrations` and `migrate manage.py migrate` first before you start the server, then each time the form submitted successfully, refresh the admin site to see if it got update yet. It would look something like this:

image

image

**Comment by Yellowatch** [comment]
I've noticed the pyc files are back, could you remove them from git tracking. 
image

**Comment by Yellowatch** [comment]
Also, I've done makemigrations and migrate, and then tested sending a form, however, the backend still doesn't show my quote

**Review by kimt12531 — APPROVED** [review]

**Review by Yellowatch — APPROVED** [review]

**Pull request merged**
