### PR TITLE
chore/MCW-356 homepage revisions

### PR DESCRIPTION
**Pull request by kimt12531**
Changes for the homepage as documented by the admin

Updates:

- new photos for gallery
- welcome section in homepage for frontend and backend for admin
- implement multiple paragraph frontend rendering for flavours and servings description from backend
- backend for about us homepage section
- backend for gallery homepage section
- color changes for gallery
- black version of square button for tablet
- remove white arrow for gallery homepage section
- fix frozen slider before interaction by moving the get request and conditional rendering

image
image
image
image

### CODE REVIEW

**Review by Yellowatch — COMMENTED** [review]
Hmmm for some reason the image isn't loading for me 
image

**Review by quangminhduong — APPROVED** [review]
Look nice!

**Comment by kimt12531** [comment]
> Hmmm for some reason the image isn't loading for me image

Could you check the backend? There should be a photo uploaded to Homepage Welcome Section. If not, let me know. Also make sure you pull the latest changes.

**Comment by Yellowatch** [comment]
okay yeah it loads now, and I've noticed you've implemented functionality for loading. Would you prefer that over the loading in the new pull request? Also, Im having issues with one of the titles not loading for some reason:
image

**Comment by Yellowatch** [comment]
image

**Pull request merged**
